### ISSUE TITLE
Minor bug in line 185, seq.py, Fff call with missing parameters

### ISSUE THREAD

**Issue by lklamt** [LJMUAstroecology/flirpy#1]
Hi,
this is a really cool and handy package. Thank you!
 Nevertheless, there is a minor bug in line 185, seq.py.

> Fff(chunck)

should be called with paramters such as height and width, otherwise the package will not work for cameras of different picture size such as

> Fff(chunck, height=self.height, width=self.width)

Best regards

**Comment by jveitchmichaelis** [comment]
Thanks, fixed!

https://github.com/LJMUAstroecology/flirpy/commit/7dc84bbef92a1cd3fc3a438e5464b02965196716
