### ISSUE TITLE
AttributeError: 'Boson' object has no attribute 'get_external_sync_mode'

### ISSUE THREAD

**Issue by Harsh188** [LJMUAstroecology/flirpy#100]
The latest commit https://github.com/LJMUAstroecology/flirpy/commit/4a972119da97cd5d5e635e7677cf77d55a63f7bf has not been reflected in the pypi package.

If I install Flirpy using pip, I get an error when trying to get the external sync mode.

**Comment by jveitchmichaelis** [comment]
If you need to use pip, for example in project requirements, you can install via pip+git for now e.g.

`pip install git+<repo-url>`
