### ISSUE TITLE
Cannot capture from lepton

### ISSUE THREAD

**Issue by elitearmedforce** [LJMUAstroecology/flirpy#29]
Hello,
I tried Flirpy today and noticed some weird issues. Honestly, I don't know how to fix it, please help!!!. (Details and screenshot attached below)

Device/installation details:
Host OS: Ubuntu 20.04.1 (dual boot)
FLIR device: FLIR Lepton 3.5
I/O hardware: Groupgets PureThermal 2
Opencv 4.3.0 installed on the host. Although not need if opencv-python-headless is installed
Python: 3.8.2 & PIP: v20.... something

Screenshot(tried both usb3.0 & usb 2.0)
![image](https://user-images.githubusercontent.com/61043834/94316399-520cc500-ff95-11ea-9be5-4393c51c289c.png)

**Comment by jveitchmichaelis** [comment]
This is due to newer versions of OpenCV/Python. Can you try a `pip install --upgrade flirpy`?

**Comment by elitearmedforce** [comment]
Appreciate ur immediate response. Just installed today, v0.2.2. FYI, using python3 and pip3. 

>This is due to newer versions of OpenCV/Python and the arguments to cv2.VideoCapture.set(), the True/False should be 1.0/0.0.

As per this comment, i understand that i should be using older version of flirpy?????


![image](https://user-images.githubusercontent.com/61043834/94318729-33f59380-ff9a-11ea-89e6-898ac3455bb6.png)

**Comment by jveitchmichaelis** [comment]
Oh perhaps this was only fixed for the Boson driver not the Lepton. I'll take a look. For now just replace True with 1 and False with 0 where python is complaining.

**Comment by jveitchmichaelis** [comment]
FYI this is now pushed to PyPI v0.1.3
