### ISSUE TITLE
Can't capture image on raspberry pi

### ISSUE THREAD

**Issue by csedwar** [LJMUAstroecology/flirpy#30]
Installed via pip install flirpy - appears to have installed with no issues, though manually needed to install exiftools.  Is this related to bug #29?

It appears that all the tests pass when I run the pytest suite as described.  But when I run the following example code:

from flirpy.camera.lepton import Lepton
camera = Lepton()
img=camera.grab()
camera.close()

I receive this warning on he command line:
[ WARN:0] global /tmp/pip-wheel-1xaftst0/opencv-python-headless/opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video1): can't open camera by index

in my jupyter noebook I get this error
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-f39df82663f7> in <module>
      2 
      3 camera = Lepton()
----> 4 img=camera.grab()
      5 camera.close()

~/.local/lib/python3.7/site-packages/flirpy/camera/lepton.py in grab(self, device_id, telemetry_mode, strip_telemetry)
    154 
    155         if self.cap is None:
--> 156             self.setup_video(device_id)
    157 
    158         res, image = self.cap.read()

~/.local/lib/python3.7/site-packages/flirpy/camera/lepton.py in setup_video(self, device_id)
    110         # The order of these calls matters!
    111         self.cap.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc(*"Y16 "))
--> 112         self.cap.set(cv2.CAP_PROP_CONVERT_RGB, False)
    113 
    114     def decode_telemetry(self, image, mode="footer"):

TypeError: Argument 'value' must be double, not bool

**Comment by csedwar** [comment]
simply not live yet in the pip repo.  fixed by cloning the git repo and doing a pip install .

**Comment by jveitchmichaelis** [comment]
Should be pushed now, sorry about that! v0.1.3

**Comment by csedwar** [comment]
No worries at all! This toolkit is great.  It is already saving me a ton of time. Everything else out there is so painful!

Eventually I want to capture data from ~4-6 leptons and tag it with a GPS, so am awaiting the list enumeration as well! If I get a little time i'll take a stab at it. 

If you have suggestions for methods to do this efficiently and write out the data I'd be all ears. It appears there is some exif support here but its not super clear to me how to use it just yet.

**Comment by jveitchmichaelis** [comment]
List enumeration in principle is easy, I've just not gotten around to it. The code now should be able to find all devices with a particular USB VID/PID, so it's just a matter of matching those to the devices returned by V4L (or DShow).

Writing data really depends on what sort of frame rates you're working with. Leptons are only 9Hz and the images are quite small, so you could just store them as single files. FLIR stores sequences as stacks (literally SEQ=sequence) of images with some header information. If you store your images as 16-bit (radiometric) TIFFs then you can add geotags in the EXIF, that's probably what I'd recommend. You can use whatever encoding you feel like, e.g. store the pixel values in Kelvin*100 which gives you a max temp of around 300C.

**Comment by csedwar** [comment]
Yeah adding geotags to the tiff is what I was thinking. Perhaps a multiband tiff for each lepton. Frame rates are slow. 1 set in 1 second or so. 

Thanks for the thoughts!
