### ISSUE TITLE
Question about the generalization of this code

### ISSUE THREAD

**Issue by ljc19800331** [LJMUAstroecology/flirpy#31]
Hello. Is this code adaptive to the FLIR E8-XT thermal camera? It seems this code is only adapted to a certain camera (maybe I am wrong). Is there any example code that can show to be used in a more general FLIR thermal camera? Thanks.

**Comment by jveitchmichaelis** [comment]
No, sorry. This library is only for FLIR's camera cores. If the FLIR E8-XT has an API or libary then I would welcome pull requests, but I can only support cameras I have access to/have an accessible API.

You can look at FLIR's Atlas SDK for E8 support I think: https://www.flir.com/support-center/Instruments/which-flir-cameras-are-supported-by-the-atlas-sdk/
