### ISSUE TITLE
Wrong header information to read the fff file.

### ISSUE THREAD

**Issue by Ikhwansong** [LJMUAstroecology/flirpy#47]
Thank you for your kind help last time.

I got the new issue that when i read the raw numpy array by the function get_image(), the output result was wrong.

![image](https://user-images.githubusercontent.com/39337513/110606501-98658180-81cd-11eb-9b35-0a946bfc977b.png)

This is the output example which has the one vertical slip and please see the upper side, there are two black rows with some white scatters. (note that all values above 12000 were cut off to better viewing and applied normalization to stretch 0 to 255)

Probably, our seq values follow the range of 6500 - 16300. The white scatters have very high values (e.g., 13107, 16242, ... etc) 
Maybe the white scatters were originally included in the whole image. But the unknown reason induces this phenomenon.

I attached the fff file with meta data and it's output image. 

Refer...
I confirmed it was correct when i converted the seq file to the mat files which are read by hdf5storage library. 

https://drive.google.com/drive/folders/1LE0rytJa5Fz-Rs1u38qBDJ0JJzfoK7Xv?usp=sharing

**Comment by jveitchmichaelis** [comment]
It's been a long time, but I believe this is now fixed. With the latest version of Flirpy (not published to pypi):

![image](https://github.com/LJMUAstroecology/flirpy/assets/3159591/c94a0b2a-1421-4e3a-9912-c66d02849bb2)
