### ISSUE TITLE
AttributeError: type object 'Boson' has no attribute 'logger'

### ISSUE THREAD

**Issue by kkats-mech** [LJMUAstroecology/flirpy#55]
## Branch: main

**Describe the Issue**
While using the Boson camera, when I am trying to grab a frame with grab() function, the issue depicted below is displayed:
![image](https://user-images.githubusercontent.com/81621369/130959021-fe324b15-fe2d-43de-884e-e2883e016e6f.png)  

**To Reproduce**
Steps to reproduce the behavior (script):

```bash
import cv2
from flirpy.camera.boson import Boson
import numpy as np

with Boson() as camera:
    while True:

        img = camera.grab().astype(np.float32)
        img = 255 * (img - img.min()) / (img.max() - img.min())
        img = img.astype(np.uint8)

        if cv2.waitKey(1) == 27:
            break  # esc to quit

    cv2.destroyAllWindows()

```

**Expected behavior**
When the code is running properly, the expected behaviour is to grab the camera frames while looping.

**Proposed solution** 
In the **boson.py** I commented the __@classmethod__ in *line 130* prior to *def find_video_device(self)* and the issue was resolved.

**Comment by jveitchmichaelis** [comment]
This should be fixed now.
