### ISSUE TITLE
ValueError: Lepton not connected (Pi4)

### ISSUE THREAD

**Issue by Tylersuard** [LJMUAstroecology/flirpy#60]
Hello.  My lepton is definitely connected.  I am using the breakout board.  Flirpy cannot find it.  How can I fix this?

**Comment by jveitchmichaelis** [comment]
If I understand correctly, you're using the breakout board (SPI) and not a
Purethermal carrier? Flirpy currently doesn't support direct comms with the
Lepton. Sorry, this is still on the todo list

**Comment by jveitchmichaelis** [comment]
See https://github.com/LJMUAstroecology/flirpy/issues/14 - duplicate issue
