### ISSUE TITLE
TAU2 no recognized

### ISSUE THREAD

**Issue by rafariva** [LJMUAstroecology/flirpy#71]
Hi , i am trying to use the code with a FLIR TAU2, connected using the USB cable in a windows. and i get the follwing error

usb.core.NoBackendError: No backend available

just with this two lines of code

```
from flirpy.camera.tau import TeaxGrabber
camera = TeaxGrabber()
```

any help?

**Comment by Saswata2303** [comment]
DId you find any solution to the problem? I am also facing the same issue.

**Comment by jveitchmichaelis** [comment]
This is an issue with libusb. You need to make sure you've installed it properly.

**Comment by jveitchmichaelis** [comment]
Closing as not a flirpy issue.
