### ISSUE TITLE
per pixel tempreature data

### ISSUE THREAD

**Issue by Bridge313** [LJMUAstroecology/flirpy#74]
How do I retrieve per pixel temperature readings from the captured Lepton image?

**Comment by jveitchmichaelis** [comment]
Are you using a PureThermal? If so then the pixel values should already be in temperature units, just scaled.

**Comment by Bridge313** [comment]
I am using flir letpon 3.5 and a PureThermal Mini

What is the scaling that would need to be applied to `image` to get the celcius temperature values.

```
from flirpy.camera.lepton import Lepton

camera = Lepton()
image = camera.grab()
```

**Comment by jveitchmichaelis** [comment]
Should be a factor of 100 and that gives you the value in Kelvin, so subtract 273 to get C.

**Comment by jveitchmichaelis** [comment]
Hi @Bridge313 - please close the issue if you got this working, thanks!
