### ISSUE TITLE
Radiometric Boson - change output mode

### ISSUE THREAD

**Issue by sophiefbm** [LJMUAstroecology/flirpy#77]
Hey (: 
I recently got a radiometric boson, but I'm not sure how to change the output modes. 
The official documentation states that there are two functions  ( TLinearSetControl(FLR_ENABLE_E.FLR_DISABLE) and radiometrySetTempStableEnable(FLR_ENABLE_E.FLR_DISABLE)), that would cover my issue. Is there any chance that you would add these two function to flirpy? Or maybe they even exist and I just didnt realize it? 

Many greetings and thanks for your work, Sophie

**Comment by jveitchmichaelis** [comment]
Apologies this got ignored for so long! I responded to another user with some suggestions but it'd be great if we could test this. Flirpy was written before the radiometric bosons were released, so the functions don't exist. I suggest moving any further discussion to this issue:

https://github.com/LJMUAstroecology/flirpy/issues/87
