### ISSUE TITLE
Duo R Support

### ISSUE THREAD

**Issue by mcherep** [LJMUAstroecology/flirpy#91]
I'm sorry if I'm missing something obvious. The documentation says that the library has been tested on FLIR Duo Pro R, but I can't find any examples. I only need to grab an image and return the average temperature.

**Comment by jveitchmichaelis** [comment]
The Duo doesn't support live streaming over USB, but flirpy can process the saved SEQ files. This is a limit of the camera unfortunately.

**Comment by mcherep** [comment]
Thanks for replying so quickly, it's great (and sad) to know.

**Comment by jveitchmichaelis** [comment]
If you just need to grab an image, then either the Lepton or Boson-R would do, depending on whether you need the resolution (or if you also need an RGB image, but that can be a lot cheaper to add on).

**Comment by mcherep** [comment]
Thank you so much! I have some cameras around, so I'll try to go with these.
