### ISSUE TITLE
FLIR ONE Edge Pro

### ISSUE THREAD

**Issue by mikelmujika11** [LJMUAstroecology/flirpy#96]
Hi,

I am interested in buying a thermal camera, but before I buy it I need to make sure that I can access the camera information (frame + temperature values) through Python using OpenCV. Does this library support this type of cameras?

Thanks

**Comment by jveitchmichaelis** [comment]
Flirpy does support this but not for the Edge Pro. You would need to use one of the "camera cores" like the Lepton or Radiometric Boson.

**Comment by mikelmujika11** [comment]
I thought they were like the TOPDON cameras that in addition to connecting to the cell phone can also be connected to the PC. Do you know of any Flir cameras that are currently sold, with similar features to the Edge Pro, that can be connected to the PC and accessed?

**Comment by jveitchmichaelis** [comment]
Sorry, no idea about TOPDON. Either way, at this time Flirpy does not support access. It's possible that the camera is a UVC device, in which case you could retrieve imagery but I doubt it returns thermometry without a library.

What features do you need? Happy to give suggestions but I'd need specific requirements. As I suggested, both the Lepton and Boson R return radiometric images and both work with OpenCV through various means. Most of these smaller consumer cameras use a sensor like the Lepton - eg 320px, 9fps. You don't get RGB/MSX but that's cheap to add with a second camera.

Your other option is to look at FLIRs APIs (see Atlas) if they exist and write your own wrapper to talk to OpenCV.

https://www.flir.com/developer/mobile-sdk/ it exists for mobile at least.

Or just buy a TOPDON and use a different library - I'd be happy to work to add support but as I don't own one, I can't do any physical testing.

See https://github.com/leswright1977/PyThermalCamera

**Comment by mikelmujika11** [comment]
I have found FLIR to be quite limited so I will look for another brand.

thanks for everything

**Comment by jveitchmichaelis** [comment]
No problem, I don't have any affiliation with any of these companies. If you do buy something, happy to try and add support into Flirpy if we can get it going.

I would say that FLIR's camera cores tend to be pretty good, if expensive, and the interfaces are well documented.
